#Define the currency denomination and its unique class ID 

item {
    #Currency denomination
    name:'10'
    #Unique ID for ₹10 note 
    id:1
}
item {
    #Currency denomination
    name:'20'
    #Unique ID for ₹20 note 
    id:2
}
item {
    name:'50'
    #Unique ID for ₹50 note 
    id:3
}
item {
    name:'100'
    #Unique ID for ₹100 note 
    id:4
}
item {
    name:'200'
    #Unique ID for ₹200 note 
    id:5
}
item {
    name:'500'
    #Unique ID for ₹500 note 
    id:6
}